kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCK1dfjYt7IGaCe2hIXGYvnElvHCbU+ydZD/v3G/zXej7Xe/k/jeiddFP/cHEK5TDl18lpWzFKP0YKsqS6L3+Vo4+VzRxaaeeMBTX4YUazJlw8jmIjkO3RPy8nczYKkQ5FznWRBqH0LMYcrUrU93jQcgCd5pxy+cn7EHUCB0b19DVzVg0FqZmszknwLu+s8CvB1WD+OhSTNj4+v3NEiy9w5xahOEothVfDmA7sCZqLtXIbNutUrrApqZMo59LanMO4UcqmZ5IOVqHnpNLpsz7RAfAZ+GrWYmOv9PAfZ1RIaqa6MpCo/6Jsa0kr8N8glRmOJK88YsI5Cz0BBHVeMbSg8HUI6Jr1ce2frIHrCLdE9rz0i6i6HPTyGRCv5inR7l45l0g/0vMY/WV8ck5/ok+M8ql1j+RuRE+2zIB3wrPcaMOt5IIZMcRks218OCuz3yJHxs+X6JyauvT3o2S9y/iDKbsYW88XC63P0S0ErbGk4MLj4uTWuIzvn2YYMfp8in4/oHh7gHsXXAWJ066DeklvNcRVwZsKM26lwRolMbU/rw2epbix4sJGxkGvqIlO9Cg6z55Sbeec7MswcBKIRgyBx06e9HbY55S3nX5GR0+W3gOqhsSvp/rvSq6dQsSZhpSKc/sJXwg0C5tiaS0kK5HxAr7YZp8OB7zzgNzGwkv5gAJ9aQmSqg73TWtOwMkJrLlU1peI8y9MMIVDfcrXBsaGtT2hjs5Sl3LQqdmPA3DqvNw==
    postgresql-postgres-password: AgB1Lz3A35ygKuc4mxQO2AYf6irOJWOr7KrwcuPkkf/+MzFDKrqt8G8++Va345vDuYOi3so+AQj2P1Xn+FMckctnhcR11uww7CInd/hP0NrGXk5rwE1o/jRb2/dDNcbq7nspZv9ARTgJQCGI7U8zDB2PDVv2Yu4uN+eL1/3upa2/QNkrCVHbsmWkAXqisuz8XLfw+NT95CA/BcVqUQZVZToMovNe4ICw7f4jVgY8q0g+p/2sXKAMsRV+EEg5UljM+/+hFzcnj0JgI5i8qQuiXuqjaON5rRR8aSU7VXO/dRbjJaFC3tr0siYPU5EwFdzNC1JSnUK548s+IswPINAMmaclcqRxDlPk68ER0Cr0TGEJa84LDYWXeAVW57KSjkr+5MRTvjfqX/wk7bnr5aZzdROT96NLX2tX/R3xhY2Sd2pMCG0PYwYHtBJDpDnr4b31evbtt91C/EU3gY9YSaHzhNBtMcxRR1E7MEN6kMszG9SQGnHdcYPkdl0bEarFaREcdvwfwVMV02eVcSgHFPZFZgZTWQVRXwhPj8svpl41nNlXcjbwjmojDScuutqY+brPg9H5sQY8WYEVM6MqNbpqDjRbK9viUDctIIbeqBFr42pCMkIzRZvtV0LoBSZ5rVigp94cBlr7nBTBcAvuTiXah9Ey+4sDc2XJVSCfRTnodTXnNHulTpwuzq9Meu1B0o9yz0mdFeWeeRkrGwhpd0odqKy9AGh5cfpgYeaBAyVb+oEItg==
