kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB6LI9uAluvDqO4vc0pks4KKxk0M/gaSPe2fwi3X8Rl1m4caDz9KJzrNIjjfH1qGtdr4JR5l170vN14q0kTRhlUqiZ/DVkCUfM/63ZlPie5l/H/BcLxPhGAubpFSoyW9HIqx3LOmSD1B15POAx07WLF99IfCOI0WmfjcfBagQVPWv/VFG7a55dtrWNN4KLlLihvKevlso/3//M9X0wLwS4a1wEcFwach1RdqVjCfJP94oI2d8fhYq/9uckJRPeBZWChp3YpPHKXXVJuqkM0IIFtnfJwfNPWBs7imn6ZgW278ZZ8jxYXIMcFtEhs3MoBaHo4cMLbK1sVJkfv6YXi4j0c/VvpDYBvNphgabuBk4GQ/29Q8Z4YMmYZjnofjaMG2TAvSqdD/5ZepsEV73xjVyhXbci6FPqWkoOb9QThVBb/PTtrU3Cns+Aps1ciUSr2awWJRZe1ENUbtqSlfc13iN64qfzucI9nWsStD/pQTlzn9zhXhiVwLTaB5Zn/EXJBP2RN9u339jXPPQRDkSyu2zkDcqJNR0hrF33AcwVehdAVIMg3XtPQydET/OHqysX3JNx7IxYb+10GpBfs1fA/xvbqro7B1E6WNh+b+627lsp0B1VCtd3lotc+XVhZFxdcBLgXEk1ht8JFCFar5jbq5+DjRQbG2RxNYS1lMXqQ9/Vj/Kw1fLp9KxXdw81rEZvLTYTVEqmz8Roj9A==
    admin-user: AgCIjtCKkN/MOkujChQgzGPMSYiydGhhxbHSN/13CHqYKVPvW/Zypy5mpXizolKT82JZhBnSQOkx/QjUqX+LBe0g7ae26OkGEwmZe3uWpN5ihuVL3XM8bKGhPMCTrsLORDQb42KQThv4iERHoIu30qEIS0OYpYHzPyh13ISMDpBfyHcPOZXPTKHXDo7Zva/N+7ZUq6ZutIfdnF8Z/UZ2kXFQwltb0CgR1ZpLTxohYuazWewAFpLbXqJeLd+XyZi6xTlPm/pM+fw47yI3vr1CHGZBd1F4dARsO6OfWKENxZI6p6TlVQokaXCvcByB+6qSiZgnTB4A5I2Wml8XkOlGOWXzRoEAQ/fLaDnh7s3KOtBFy/Q01eNElxXXsHe7d1NjTvJr8s1VSPe+qvnzTYPMjRKtNnc//czGpuRRFZY95O3UdkYHnnU2LVy7zvC0d6Af7BkthKjMS/Fetku3mg4GGlJoIWw4ieQLlFl2lK0DBguP6n9c2jD7MvbPLmGceySD5MdYoXd2Rb6d9ZEE1BdbsC6fajVOFDR9KSRyq695gj8FHoSb1GNPopqe0E91N/eAf5DSyBSTifnNvWztvy+lQqaLwfLc+s3VpWcbjco8qk11d+BD9IzMBa9N/BQE8l/+tcYVQby7aReyVmDsnjcnH2Lv+HLyuoozmSX3tpStdS4sAQM0PBAMwzYKwtwJQJFm3RoA9bmYog==
